version: '3.8'

services:
  echo:
    image: jmalloc/echo-server

  app:
    image: elixir:1.12.0-rc.1
    environment:
    - 'ERL_AFLAGS=-kernel shell_history enabled'
    volumes:
    - ./:/app
    working_dir: /app
    command: bash -c "mix local.hex --force && mix local.rebar --force && tail -f /dev/null"
